import { createSlice } from "@reduxjs/toolkit";
import img1 from './akot.jpg';
import img2 from './dr.jpg';
import img3 from './jaws.jpg';
import img4 from './lotr.jpg';
import img5 from './m22.jpg';
import img6 from './sw.jpg';
import img7 from './tm.jpg';
import img8 from './xm.jpg';
import Movie from "./TheMovie";
const myKit=createSlice({
    name:"List",
    initialState:{
        mySet:[
            new Movie(img1,"A knight's tale","After his master dies, a peasant squire, fueled by his desire for food and glory, creates a new identity for himself as a knight.Inspired by The Canterbury Tales', as well as the early life of William Marshall (later First Earl of Pembroke), this is the story of William, a young squire with a gift for jousting."," After his master dies suddenly, the squire hits the road with his cohorts Roland and Wat. On the journey, they stumble across an unknown writer, Chaucer. William, lacking a proper pedigree, convinces Chaucer to forge genealogy documents that will pass him off as a knight. With his newly-minted history in hand, the young man sets out to prove himself a worthy knight at the country's jousting competition, and finds romance along the way","8.4/10","heath Ledger,Mark Addy,Shannyn Sossamon,Paul Bettany,Rufus Sewell","https://archive.org/embed/AKnightsTaleTrailer"),
            new Movie(img2,"Dracula","The centuries old vampire Count Dracula comes to England to seduce his barrister Jonathan Harker's fiancée Mina Murray and inflict havoc in the foreign land.","The centuries old vampire Count Dracula comes to England to seduce his barrister Jonathan Harker's fiancée Mina Murray and inflict havoc in the foreign land.This version of Dracula is closely based on Bram Stokers classic novel. Young barrister Jonathan Harker is assigned to a gloomy village in the mists of eastern Europe. He is captured and imprisoned by the undead vampire Dracula, who travels to London, inspired by a photograph of Harker s betrothed, Mina Murray. In Britain, Dracula begins a reign of seduction and terror, draining the life from Mina s closest friend, Lucy Westenra. Lucys friends gather together to try to drive Dracula away.","6.3/10","Gary Oldman,Winona Ryder,Anthony Hopkins,Keanu Reeves","https://www.youtube.com/watch?v=4166M7xMEuc"),
            new Movie(img3,"Jaws","When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
            "Nighttime on Amity Island. A bonfire rages as a group of teens gather around for an evening of fun, drinking, and the pursuit of each other. One of those pursuits involves a blond girl named Chrissie being chased by a guy who has caught her eye across the rising flames from the fire. His chase becomes even more intent when Chrissie starts disrobing while still running toward the shore. As she splashes into the water for a nude swim under the moonlight, the consumption of booze proves too much for her admirer who trips, falls and ultimately passes out before he can enjoy the fruits of temptation offered by a young naked woman in the ocean.","8.7/10","Roy Scheider, Robert Shaw ,QuintRichard Dreyfus , Gary Ellen, Murray Hamilton","https://archive.org/embed/TheLordOfTheRingsTrilogyTrailer"),
            new Movie(img4,"lord of the rings","A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.","In the Second Age of Middle-earth, the lords of Elves, Dwarves, and Men are given Rings of Power. Unbeknownst to them, the Dark Lord Sauron forges the One Ring in Mount Doom, instilling into it a great part of his power, to dominate the other Rings so he might conquer Middle-earth. A final alliance of Men and Elves battles Sauron's forces in Mordor. Isildur of Gondor severs Sauron's finger and the Ring with it, thereby vanquishing Sauron and returning him to spirit form. With Sauron's first defeat, the Third Age of Middle-earth begins. The Ring's influence corrupts Isildur, who takes it for himself and is later killed by Orcs. The Ring is lost in a river for 2,500 years until it is found by Gollum, who owns it for over four and a half centuries. The ring abandons Gollum and it is subsequently found by a hobbit named Bilbo Baggins, who is unaware of its history.Sixty years later, Bilbo celebrates his 111th birthday in the Shire, reuniting with his old friend, the wizard Gandalf the Grey. Bilbo departs the Shire for one last adventure, and he leaves his inheritance, including the Ring, to his nephew Frodo. Gandalf investigates the Ring, discovers its true nature, and learns that Gollum was captured and tortured by Sauron's Orcs, revealing two words during his interrogation: Shire and Baggins. Gandalf returns and warns Frodo to leave the Shire. As Frodo departs with his friend, gardener Samwise Gamgee, Gandalf rides to Isengard to meet with the wizard Saruman, but discovers his alliance with Sauron, who has dispatched his nine undead Nazgûl servants to find Frodo.","8.5/10","Elijah Wood Ian Kellen Liv Tyler Viggo Mortensen Sean Astin","https://www.youtube.com/embed/7v1hIkYH24"),
            new Movie(img5,"Mile 22","A small team of elite American intelligence officers, part of a top-secret tactical command unit, try to smuggle a mysterious police officer with sensitive information out of Indonesia.","CIA Agent James Silva leads a top secret CIA Special Activities Division unit, code-named Overwatch, to infiltrate a Russian Federal Security Service (FSB) safe house in the United States. Under the supervision of James Bishop, Overwatch's mission is to locate and destroy shipments of cesium before the highly toxic substance can be weaponized to kill thousands. The unit kills the occupants, while Overwatch Agent Alice Kerr is wounded. One of the Russians, an 18-year-old named Anatole Kuragin, falls out of a window during an explosion after failing to save the cesium. Silva executes Kuragin despite his pleading, and everyone escapes.","7.9/10","Mark Wahlberg, Iko Uwais, John Malkovich, Lauren Cohan, and Ronda Rousey","https://www.youtube.com/watch?v=kXdhcpNLICQ"),
            new Movie(img6,"Starwars","In a time of conflict, a group of unlikely heroes band together on a mission to steal the plans to the Death Star, the Empire's ultimate weapon of destruction.","The main Star Wars film series is a trilogy of trilogies; as it neared completion, it began to be referred to as the 'Skywalker Saga' by Disney.[1][2] It was released beginning with the original trilogy (Episodes IV, V and VI, 1977–1983), followed by the prequel trilogy (Episodes I, II and III, 1999–2005) and the sequel trilogy (Episodes VII, VIII and IX, 2015–2019).[a] The first film released, Star Wars (1977), is the fourth film chronologically and was later subtitled Episode IV – A New Hope. The saga begins chronologically with Star Wars: Episode I – The Phantom Menace (1999) and concludes with Episode IX – The Rise of Skywalker (2019).","9.0/10","Kathleen Kennedy, J. J. Abrams and Bryan Burk","https://www.youtube.com/watch?v=8Qn_spdM5Zg"),
            new Movie(img7,"The mexican","A man tries to transport an ancient gun called The Mexican, believed to carry a curse, back across the border, while his girlfriend pressures him to give up his criminal ways.","In Los Angeles, a traffic light changes to red and there are offscreen sounds of an automobile collision.Five years later, Jerry Welbach has been working off a debt to imprisoned mob boss Arnold Margolese. After Jerry fouls up what was meant to be his final errand, Margolese's second-in-command, Bernie Nayman sends Jerry on a new final errand: retrieving an antique pistol for Margolese in Mexico from a man named Beck. Jerry's additional job for Margolese proves to be the last straw for Jerry's girlfriend Sam, who leaves him to move to Las Vegas.Arriving in Mexico, Jerry finds the pistol with Beck, who explains the history of the legendary gun known as 'the Mexican'. When Beck is killed by a stray bullet from celebratory gunfire, Jerry calls his colleague Ted and learns that Beck was Margolese's grandson. Just then, Jerry's car is stolen, with Beck's body and the pistol inside. Jerry recovers the car and the gun, shooting one of the thieves in the foot and burying the body","7.6/10","Brad Pitt, Julia Roberts","https://www.youtube.com/watch?v=BXoTjx6yWzo"),
            new Movie(img8,"X-men","In a world where mutants (evolved super-powered humans) exist and are discriminated against, two groups form for an inevitable clash: the supremacist Brotherhood, and the pacifist X-Men.","In 1944 Nazi-occupied Poland, 13-year-old Erik Lehnsherr is separated from his parents upon entering the Auschwitz concentration camp. While attempting to reach them, he causes a set of metal gates to bend toward him because of his mutant ability to generate magnetic fields, but is knocked out by the guards. In the not-too-distant future, U.S. Senator Robert Kelly attempts to pass a 'Mutant Registration Act' in Congress, which would force mutants to reveal their identities and abilities. Present are Lehnsherr, now going by the name 'Magneto', and his telepathic colleague Professor Charles Xavier. Xavier sees Lehnsherr in attendance and is concerned with how he will respond to the Registration Act.","8.0/10","Hugh Jackman, Patrick Stewart, Ian McKellen, Halle Berry, Famke Janssen","https://www.youtube.com/watch?v=UrbHykKUfTM"),
             ]
    },
    reducers:{
        search(state,action){
            state.mySet=[...state.mySet.filter(element=>element.name.includes(action.payload))]
        },
        add(state,action){
            state.mySet=[...state.mySet,new Movie(action.payload.image,action.payload.name,action.payload.description,
                action.payload.summary,action.payload.note,action.payload.actors,action.payload.video)]
        }
    }
})
export const {search,add}=myKit.actions;
export default myKit.reducer